version = "0.3.2"

[scripts]
dev.cmd = [
	"cd examples/simple",
	"perseus %command"
]
dev.args = [ "command" ]
dev.desc = "runs the `simple` example with whatever Perseus CLI command is provided"

release.cmd = "standard-version --sign --commit-all && git push --follow-tags %% origin main"
release.desc = "creates a new project release and pushes it to github (cargo version must be manually bumped)"

publish.cmd = "cargo publish"
publish.desc = "publishes to crates.ioo"