[package]
name = "perseus-size-opt-example-simple"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = "0.3.0-beta.17"
sycamore = "0.6"
perseus-size-opt = { path = "../../" }